export function generateHeader(): string {
  return `/**
 * --------------------------------------------------
 * THIS FILE IS AUTO-GENERATED.
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Generated by:
 *
 * npm run atlas:build
 *
 * --------------------------------------------------
 */

`;
}