import { mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, resolve } from "path";

const destination = resolve(
  process.cwd(),
  "app/components/map/lib/atlas/generated/settlements.ts"
);

const files = [
  "south.json",
  "east.json",
  "north.json",
  "west.json",
  "central.json",
];

const settlements = files
  .flatMap((file) =>
    JSON.parse(
      readFileSync(
        resolve(
          process.cwd(),
          "data/world",
          file
        ),
        "utf8"
      )
    )
  )
  .sort((a, b) =>
    a.name.localeCompare(b.name)
  );

const output = `/**
 * --------------------------------------------------
 * THIS FILE IS AUTO-GENERATED.
 *
 * Generated by:
 *
 * npm run atlas:build
 *
 * Do not edit this file manually.
 * --------------------------------------------------
 */

import type { Settlement } from "../locations/types";

export const SETTLEMENTS: Settlement[] =
${JSON.stringify(settlements, null, 2)};
`;

mkdirSync(dirname(destination), {
  recursive: true,
});

writeFileSync(
  destination,
  output,
  "utf8"
);

console.log("");
console.log("🗺️  NGS Atlas Builder");
console.log("------------------------------");
console.log(`✓ Loaded ${files.length} region files`);
console.log(`✓ Generated ${settlements.length} settlements`);
console.log(`✓ Output: ${destination}`);
console.log("");
console.log("Atlas build complete.");